import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from '@/hooks/use-toast';

export interface Group {
  id: string;
  name: string;
  description: string | null;
  type: string;
  invite_code: string;
  invite_code_expires_at: string | null;
  invite_code_single_use: boolean;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface GroupMember {
  id: string;
  group_id: string;
  user_id: string;
  joined_at: string;
  profile?: {
    id: string;
    name: string;
    email?: string; // Email is now optional - not exposed to other group members for privacy
    avatar_url: string | null;
  };
}

export function useGroups() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['groups', user?.id],
    queryFn: async () => {
      if (!user) return [];

      const { data, error } = await supabase
        .from('groups')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data as Group[];
    },
    enabled: !!user
  });
}

export function useGroup(groupId: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['group', groupId],
    queryFn: async () => {
      if (!user || !groupId) return null;

      // Use secure RPC function that hides invite codes from non-creators
      const { data, error } = await supabase
        .rpc('get_group_with_invite_code', { _group_id: groupId })
        .maybeSingle();

      if (error) throw error;
      return data as Group | null;
    },
    enabled: !!user && !!groupId
  });
}

export function useGroupMembers(groupId: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['group-members', groupId],
    queryFn: async () => {
      if (!user || !groupId) return [];

      const { data: members, error: membersError } = await supabase
        .from('group_members')
        .select('*')
        .eq('group_id', groupId);

      if (membersError) throw membersError;

      // Use secure RPC function to get profiles without exposing emails
      const { data: profiles, error: profilesError } = await supabase
        .rpc('get_group_member_profiles', { _group_id: groupId });

      if (profilesError) throw profilesError;

      // Combine members with profiles (email is no longer exposed)
      const membersWithProfiles = members.map(member => ({
        ...member,
        profile: profiles?.find((p: { user_id: string }) => p.user_id === member.user_id)
      }));

      return membersWithProfiles as GroupMember[];
    },
    enabled: !!user && !!groupId
  });
}

export function useCreateGroup() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async ({ name, description, type }: { name: string; description?: string; type: string }) => {
      if (!user) throw new Error('Not authenticated');

      // IMPORTANT: don't request the inserted row back (RETURNING) because RLS
      // SELECT policies may block returning the new row before post-insert triggers run.
      const { error } = await supabase
        .from('groups')
        .insert({
          name,
          description,
          type,
          created_by: user.id
        });

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['groups'] });
      toast({
        title: 'Group created',
        description: 'Your new group has been created successfully.'
      });
    },
    onError: (error) => {
      toast({
        title: 'Error creating group',
        description: error.message,
        variant: 'destructive'
      });
    }
  });
}

export function useJoinGroup() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (inviteCode: string) => {
      if (!user) throw new Error('Not authenticated');

      // Find group by invite code
      const { data: group, error: groupError } = await supabase
        .from('groups')
        .select('id, invite_code_expires_at')
        .eq('invite_code', inviteCode)
        .maybeSingle();

      if (groupError) throw groupError;
      if (!group) throw new Error('Invalid invite code');

      // Note: We no longer enforce expiration on invite codes
      // Codes remain valid until explicitly regenerated by the group creator

      // Check if already a member
      const { data: existingMember } = await supabase
        .from('group_members')
        .select('id')
        .eq('group_id', group.id)
        .eq('user_id', user.id)
        .maybeSingle();

      if (existingMember) throw new Error('You are already a member of this group');

      // Join the group
      const { error: joinError } = await supabase
        .from('group_members')
        .insert({
          group_id: group.id,
          user_id: user.id
        });

      if (joinError) throw joinError;
      return group;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['groups'] });
      toast({
        title: 'Joined group',
        description: 'You have successfully joined the group.'
      });
    },
    onError: (error) => {
      toast({
        title: 'Error joining group',
        description: error.message,
        variant: 'destructive'
      });
    }
  });
}

export function useRegenerateInviteCode() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (groupId: string) => {
      const { data, error } = await supabase.rpc('regenerate_invite_code', {
        group_id: groupId
      });

      if (error) throw error;
      return data as string;
    },
    onSuccess: (_, groupId) => {
      queryClient.invalidateQueries({ queryKey: ['group', groupId] });
      toast({
        title: 'Invite code regenerated',
        description: 'A new invite code has been created and will expire in 7 days.'
      });
    },
    onError: (error) => {
      toast({
        title: 'Error regenerating code',
        description: error.message,
        variant: 'destructive'
      });
    }
  });
}

export function useUpdateInviteCodeSettings() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ groupId, singleUse }: { groupId: string; singleUse: boolean }) => {
      const { error } = await supabase
        .from('groups')
        .update({ invite_code_single_use: singleUse })
        .eq('id', groupId);

      if (error) throw error;
    },
    onSuccess: (_, { groupId, singleUse }) => {
      queryClient.invalidateQueries({ queryKey: ['group', groupId] });
      toast({
        title: 'Settings updated',
        description: singleUse 
          ? 'Invite code will now regenerate after each use.' 
          : 'Invite code can now be used multiple times.'
      });
    },
    onError: (error) => {
      toast({
        title: 'Error updating settings',
        description: error.message,
        variant: 'destructive'
      });
    }
  });
}

export function useSetCustomInviteCode() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ groupId, customCode }: { groupId: string; customCode: string }) => {
      // Validate code format (alphanumeric, 4-20 chars)
      const cleanCode = customCode.trim().toLowerCase();
      if (!/^[a-z0-9]{4,20}$/.test(cleanCode)) {
        throw new Error('Code must be 4-20 alphanumeric characters');
      }

      // Check if code is already in use by another group
      const { data: existing, error: checkError } = await supabase
        .from('groups')
        .select('id')
        .eq('invite_code', cleanCode)
        .neq('id', groupId)
        .maybeSingle();

      if (checkError) throw checkError;
      if (existing) throw new Error('This invite code is already in use');

      const { error } = await supabase
        .from('groups')
        .update({ 
          invite_code: cleanCode,
          invite_code_expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
          updated_at: new Date().toISOString()
        })
        .eq('id', groupId);

      if (error) throw error;
      return cleanCode;
    },
    onSuccess: (_, { groupId }) => {
      queryClient.invalidateQueries({ queryKey: ['group', groupId] });
      toast({
        title: 'Custom code set',
        description: 'Your custom invite code is now active.'
      });
    },
    onError: (error) => {
      toast({
        title: 'Error setting code',
        description: error.message,
        variant: 'destructive'
      });
    }
  });
}
